name: "Build and Push Docker Image"
description: "Builds a Docker image"
inputs:
  context:
    description: "Path to the Docker build context."
    required: true
  repository:
    description: "Repository for the Docker image."
    required: false
  scope:
    description: "Scope or namespace for the Docker image."
    required: true
  registry:
    description: |
      Azure Registry to authenticate against.
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository from latest commit
      uses: actions/checkout@v4

    - name: Setup docker image name and downcase it
      id: setup_image_name
      run: |
        if [[ -z "${{ inputs.repository }}" ]]; then
          DOCKER_IMAGE_NAME="${{ inputs.registry }}/${{ inputs.scope }}/${{ github.event.repository.name }}:${{ github.ref_name }}"
        else
          DOCKER_IMAGE_NAME="${{ inputs.registry }}/${{ inputs.repository }}:${{ github.ref_name }}"
        fi
        echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME,,}" >> $GITHUB_ENV
      shell: bash

    - name: Build docker image
      run: docker build ${{ inputs.context }} -t ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash
