replicaCount: 1

image:
  repository: hello-world-image
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example-test.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
