name: "Run ESLint"
description: "Installs dependencies and runs ESLint"
inputs:
  node-version:
    description: "Node.js version"
    default: "20"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: npm ci
      shell: bash

    - run: npm run lint
      shell: bash
