name: Test Build and Push Docker Image

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "actions/build-docker/**"

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Login to Artifactory Action
        uses: ./actions/artifactory-login
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_PUSH_USER }}
          password: ${{ secrets.ACR_PUSH_TOKEN }}

      - name: Test Build Docker Image
        id: build
        uses: ./actions/build-docker
        with:
          context: ./test
          scope: infra
          registry: ${{ secrets.ACR_URL }}

      - name: Debug output
        run: echo "Built image $DOCKER_IMAGE_NAME"
        shell: bash

      - name: Test Push Docker Image 
        uses: ./actions/push-docker
        with:
          image-name: $DOCKER_IMAGE_NAME
