name: Test

on:
  workflow_dispatch:
  workflow_call:

      
jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint and Test Charts
        uses: MapColonies/shared-workflows/actions/helm-lint@helm-lint-v1
        with:
          chartDirs: "./test/helm"
