name: Test artifactory-login action

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Test ACR var
        id: test-variavle
        run: echo "The secret is ${{ secrets.ACR_URL }}"

      - name: Test Login to Artifactory Action
        id: test-artifactory-login
        uses: ./actions/artifactory-login
        env:
          ACR_URL: ${{ secrets.ACR_URL }}

