name: Test artifactory-login action

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - "actions/artifactory-login/**"
      - ".github/workflows/test-artifactory-login.yaml"

  pull_request:
    paths:
      - "actions/artifactory-login/**"
      - ".github/workflows/test-artifactory-login.yaml"
    types:
      - edited
      - opened
      - ready_for_review
      - synchronize

  merge_group:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Login to Artifactory Action
        id: test-artifactory-login
        uses: ./actions/artifactory-login

